/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LockRouteImport } from './routes/lock'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCallsRouteImport } from './routes/_authenticated/calls'
import { Route as AuthenticatedChatsRouteImport } from './routes/_authenticated/chats'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedDevicesRouteImport } from './routes/_authenticated/devices'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedChatIdRouteImport } from './routes/_authenticated/chat.$id'
import { Route as AuthenticatedGroupIdRouteImport } from './routes/_authenticated/group.$id'
import { Route as AuthenticatedSecurityIdRouteImport } from './routes/_authenticated/security.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LockRoute = LockRouteImport.update({
  id: '/lock',
  path: '/lock',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCallsRoute = AuthenticatedCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatsRoute = AuthenticatedChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevicesRoute = AuthenticatedDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatIdRoute = AuthenticatedChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupIdRoute = AuthenticatedGroupIdRouteImport.update({
  id: '/group/$id',
  path: '/group/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecurityIdRoute = AuthenticatedSecurityIdRouteImport.update({
  id: '/security/$id',
  path: '/security/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/lock': typeof LockRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/chats': typeof AuthenticatedChatsRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/chat/$id': typeof AuthenticatedChatIdRoute
  '/group/$id': typeof AuthenticatedGroupIdRoute
  '/security/$id': typeof AuthenticatedSecurityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/lock': typeof LockRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/chats': typeof AuthenticatedChatsRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/chat/$id': typeof AuthenticatedChatIdRoute
  '/group/$id': typeof AuthenticatedGroupIdRoute
  '/security/$id': typeof AuthenticatedSecurityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/lock': typeof LockRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/calls': typeof AuthenticatedCallsRoute
  '/_authenticated/chats': typeof AuthenticatedChatsRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/devices': typeof AuthenticatedDevicesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/chat/$id': typeof AuthenticatedChatIdRoute
  '/_authenticated/group/$id': typeof AuthenticatedGroupIdRoute
  '/_authenticated/security/$id': typeof AuthenticatedSecurityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/lock'
    | '/admin'
    | '/calls'
    | '/chats'
    | '/contacts'
    | '/devices'
    | '/settings'
    | '/chat/$id'
    | '/group/$id'
    | '/security/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/lock'
    | '/admin'
    | '/calls'
    | '/chats'
    | '/contacts'
    | '/devices'
    | '/settings'
    | '/chat/$id'
    | '/group/$id'
    | '/security/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/lock'
    | '/_authenticated/admin'
    | '/_authenticated/calls'
    | '/_authenticated/chats'
    | '/_authenticated/contacts'
    | '/_authenticated/devices'
    | '/_authenticated/settings'
    | '/_authenticated/chat/$id'
    | '/_authenticated/group/$id'
    | '/_authenticated/security/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LockRoute: typeof LockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lock': {
      id: '/lock'
      path: '/lock'
      fullPath: '/lock'
      preLoaderRoute: typeof LockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calls': {
      id: '/_authenticated/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof AuthenticatedCallsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats': {
      id: '/_authenticated/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devices': {
      id: '/_authenticated/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AuthenticatedDevicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$id': {
      id: '/_authenticated/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof AuthenticatedChatIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/group/$id': {
      id: '/_authenticated/group/$id'
      path: '/group/$id'
      fullPath: '/group/$id'
      preLoaderRoute: typeof AuthenticatedGroupIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security/$id': {
      id: '/_authenticated/security/$id'
      path: '/security/$id'
      fullPath: '/security/$id'
      preLoaderRoute: typeof AuthenticatedSecurityIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCallsRoute: typeof AuthenticatedCallsRoute
  AuthenticatedChatsRoute: typeof AuthenticatedChatsRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedDevicesRoute: typeof AuthenticatedDevicesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedChatIdRoute: typeof AuthenticatedChatIdRoute
  AuthenticatedGroupIdRoute: typeof AuthenticatedGroupIdRoute
  AuthenticatedSecurityIdRoute: typeof AuthenticatedSecurityIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCallsRoute: AuthenticatedCallsRoute,
  AuthenticatedChatsRoute: AuthenticatedChatsRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedDevicesRoute: AuthenticatedDevicesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedChatIdRoute: AuthenticatedChatIdRoute,
  AuthenticatedGroupIdRoute: AuthenticatedGroupIdRoute,
  AuthenticatedSecurityIdRoute: AuthenticatedSecurityIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LockRoute: LockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
